trigger:
  branches:
    include:
      - master  # ou master selon ton repo

pool: Azure Pipelines 

variables:
  azureSubscription: 'AZURE-DEV'  # À créer dans Azure DevOps
  appName: 'APPSERVICE' 
  buildFolder: 'dist'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Installer Node.js'

- script: |
    npm ci
    npm run build
  displayName: 'Installer les dépendances et compiler Vue.js'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/$(buildFolder)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
    replaceExistingArchive: true
  displayName: 'Archiver les fichiers générés'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publier les artefacts'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux' # ou 'webApp' pour Windows
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
  displayName: 'Déployer vers Azure App Service'
